require 'ui_manage'

module UiManage
  # Renders the check catalogue for README.md.
  #
  # Generated rather than hand-written, and checked by a test, because a list
  # of this many checks maintained by hand drifts the first time someone adds
  # one.
  module Catalog
    BEGIN_MARKER = '<!-- begin: check catalog -->'.freeze
    END_MARKER   = '<!-- end: check catalog -->'.freeze

    module_function

    def markdown
      sections = Audit::Registry.all.group_by(&:category).sort_by { |category, _| category.to_s }

      body = sections.map do |category, checks|
        rows = checks.map { |check| "| `#{check.id}` | #{check.severity} | #{check.title} |" }
        ["### #{category.to_s.capitalize} (#{checks.size})", '',
         '| Check | Default severity | What it looks for |', '| --- | --- | --- |',
         *rows].join("\n")
      end

      [BEGIN_MARKER,
       '<!-- Generated by `rake catalog`. Do not edit by hand. -->',
       '',
       *body,
       '',
       END_MARKER].join("\n")
    end

    # Replaces the marked block in README.md. Returns true when the file
    # changed.
    def update(path = 'README.md')
      original = File.read(path)
      updated  = replace(original)
      return false if updated == original

      File.write(path, updated)
      true
    end

    def replace(text)
      unless text.include?(BEGIN_MARKER) && text.include?(END_MARKER)
        raise ArgumentError, "README is missing the #{BEGIN_MARKER} / #{END_MARKER} markers."
      end

      text.sub(/#{Regexp.escape(BEGIN_MARKER)}.*?#{Regexp.escape(END_MARKER)}/m, markdown)
    end

    def current?(path = 'README.md')
      text = File.read(path)
      replace(text) == text
    end
  end
end
